name: Unseeable
version: 4.5-SNAPSHOT
description: That one plugin where people just dissapear into thin air.
main: nl.lucemans.unseeable.Unseeable
author: Lucemans
commands:
   unseeable:
     aliases: [us,unsee,uns]
     description: Unseeable main command
     permission: unseeable.user
   unseeableadmin:
     aliases: [usa,unseeadmin,unsa]
     description: Unseeable main command
     permission: unseeable.admin
permissions:
   unseeable.user:
     default: true
     description: Primary user permission for Unseeable
   unseeable.admin:
     default: op
     description: Admin permissions for Unseeable